name: Processing Problem Matcher
description: Attaches a problem matcher that looks for errors during processing java builds
author: Bent Hillerkus
branding:
  icon: check-square
  color: yellow
runs:
  using: 'node12'
  main: 'index.js'
